bits/urls.py
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from . import views
from django.conf import settings
admin.autodiscover()
app_name = 'bits'
urlpatterns = [
    url(r'^$', views.get_index, name='get_index'),
    url(r'^login/$', views.authenticate, name='authenticate'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^register/$', views.register, name='register'),
    url(r'^shop/(?P<shop_item>[^/?]+)/$', views.get_product, name='get_product'),
    url(r'^shop/(?P<shop_item>[^/?]+)/(?P<shop_subitem>[^/?]+)/$', views.get_product_by_sub, name='get_product_by_sub'),
    url(r'^product/(?P<product_item>[^/?]+)/$', views.get_product_solo, name='get_product_solo'),
    url(r'^(?P<shop_item>[^/?]+)/new/$', views.get_product_by_new, name='get_product_by_new'),
    url(r'^new/$', views.get_product_by_new_solo, name='get_product_by_new'),
    url(r'^contact/$', views.contact_request, name='contact'),
    url(r'^cart/add-to-cart/$', views.add_to_cart, name='add_to_cart'),
    url(r'^cart/delete/(?P<product_item>[^/?]+)/$', views.deleterow, name='deleterow'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

webshop/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

admin.autodiscover()
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^webshop/', include('bits.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bits/models.py
from __future__ import unicode_literals
from django.db import models

NEW = (
    ('NEW', 'NEW'),
    ('NOTNEW', 'NOTNEW'),
)

CAT = (
    ('bracelets', 'bracelets'),
    ('kettingen', 'kettingen'),
)

SUBCAT = (
    ('leather', 'leather'),
    ('sil_bal', 'Silver Balled'),
    ('sil_chain', 'Silver Chained'),
    ('beads', 'Beads'),
)

# Create your models here.

class bp_pages(models.Model):
    pagina = models.CharField(max_length=200)
    inhoud = models.TextField()
    over_ons = models.TextField()

    class Meta:
        verbose_name = 'Pagina'
        verbose_name_plural = 'Paginas'

class bp_products(models.Model):
    pr_naam = models.CharField(max_length=200)
    pr_beschrijving = models.TextField()
    pr_cat = models.CharField(max_length=200, choices=CAT)
    pr_subcat= models.CharField(max_length=200, choices=SUBCAT)
    pr_prijs = models.IntegerField()
    file = models.ImageField()
    datestamp = models.DateTimeField(auto_now_add=True)
    new = models.CharField(max_length=50, choices=NEW)

    def __unicode__(self):
       return self.pr_naam

    class Meta:
        verbose_name = 'Product'
        verbose_name_plural = 'Producten'

class bp_users(models.Model):
    voornaam = models.CharField(max_length=200)
    achternaam = models.CharField(max_length=200)
    straat = models.CharField(max_length=200)
    nummer = models.IntegerField()
    postcode = models.CharField(max_length=200)
    plaats = models.CharField(max_length=200)
    username = models.CharField(max_length=200)
    password = models.CharField(max_length=200)

    def __unicode__(self):
       return self.voornaam


    class Meta:
        verbose_name = 'Gebruikers'
        verbose_name_plural = 'Gebruikers'

class ContactModel(models.Model):
    voornaam = models.CharField(max_length=200)
    email = models.CharField(max_length=200)
    onderwerp = models.CharField(max_length=200)
    text = models.TextField()

    def __unicode__(self):
        return self.onderwerp

    class Meta:
        verbose_name = 'Contactformulier'
        verbose_name_plural = 'Contactformulier'

bits/forms.py
from django import forms
from .models import ContactModel, bp_products, bp_users

MATEN = (('s', 'S - 15cm-16cm'),('m', 'M - 16.5cm-18cm'), ('l', 'L - 18cm-20cm'), ('xl', 'XL - 20cm-22cm'))

class ContactForm(forms.ModelForm):

    class Meta:
        model = ContactModel
        fields = ('voornaam', 'email', 'onderwerp', 'text')

class ShoppingForm(forms.ModelForm):
    quantity = forms.IntegerField()
    maat = forms.ChoiceField(choices=MATEN)
    pr_prijs = forms.CharField(max_length=200, widget=forms.HiddenInput())
    pr_naam = forms.CharField(max_length=200, widget=forms.HiddenInput())

    class Meta:
        model = bp_products
        fields = ['pr_prijs', 'pr_naam']

class Login(forms.ModelForm):

    class Meta:
        model = bp_users
        fields = ['username', 'password']
        widgets = {
            'password': forms.PasswordInput(),
        }

class Registreren(forms.ModelForm):

    class Meta:
        model = bp_users
        fields = "__all__"
        widgets = {
            'password': forms.PasswordInput(),
        }

bits/views.py
from django.shortcuts import render, reverse, redirect
from django.http import HttpResponseRedirect, HttpResponse
from .models import bp_pages, bp_products, bp_users, ContactModel
from .forms import ContactForm, ShoppingForm, Login, Registreren
from cart.cart import Cart
# Create your views here.
def get_index(request):
    text = bp_pages.objects.filter(pagina="home")
    former = ContactForm()
    if request.session.has_key('username'):
        username = request.session['username']
        message = "Welkom, %s" % username
    return render(request, 'bits/home.html', context=locals())

def get_product(request, shop_item):
    query = bp_products.objects.filter(pr_cat=shop_item)[:3]
    query_all = bp_products.objects.filter(pr_cat=shop_item)
    return render(request, 'bits/product.html', {'query': query, 'query_all': query_all})

def get_product_by_sub(request, shop_item, shop_subitem):
    query = bp_products.objects.filter(pr_cat=shop_item, pr_subcat=shop_subitem)[:3]
    query_all = bp_products.objects.filter(pr_cat=shop_item, pr_subcat=shop_subitem)
    return render(request, 'bits/product.html', {'query': query, 'query_all': query_all})

def get_product_by_new(request, shop_item):
    new = 'NEW'
    query = bp_products.objects.filter(pr_cat=shop_item, new=new)[:3]
    query_all = bp_products.objects.filter(pr_cat=shop_item, new=new)
    return render(request, 'bits/product.html', {'query': query, 'query_all': query_all})

def get_product_by_new_solo(request):
    new = 'NEW'
    query = bp_products.objects.filter(new=new)[:3]
    query_all = bp_products.objects.filter(new=new)
    return render(request, 'bits/product.html', {'query': query, 'query_all': query_all})

def get_product_solo(request, product_item):
    query = bp_products.objects.filter(id=product_item)
    query_naam = bp_products.objects.values_list('pr_naam', flat=True).get(id=product_item)
    query_prijs = bp_products.objects.values_list('pr_prijs', flat=True).get(id=product_item)
    if request.method == 'POST':
        form = ShoppingForm(request.POST)
        if form.is_valid():
            product = bp_products.objects.get(id=product_item)
            cart = Cart(request)
            quantity = form.cleaned_data['quantity']
            maat = form.cleaned_data['maat']
            cart.add(product, product.pr_prijs, maat, quantity)
            return HttpResponseRedirect(reverse('bits:add_to_cart'))
    else :
        form = ShoppingForm(initial={'pr_prijs': query_prijs, 'pr_naam': query_naam})
    return render(request, 'bits/solo.html', {'query': query, 'form': form})

def add_to_cart(request):
    return render(request, 'bits/cart.html', dict(cart=Cart(request)))

def contact_request(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            obj = ContactModel()
            obj.voornaam = form.cleaned_data['voornaam']
            obj.onderwerp = form.cleaned_data['onderwerp']
            obj.email = form.cleaned_data['email']
            obj.text = form.cleaned_data['text']
            obj.save()
    else:
        form = ContactForm()
    return render(request, 'bits/contact.html', {'form': form})

def authenticate(request):
    if request.method == 'POST':
        form = Login(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            if bp_users.objects.filter(username=username).exists() == True:
                if bp_users.objects.filter(password=password).exists() == True:
                    request.session['username']= username
                    url = reverse('bits:get_index')
                    return HttpResponseRedirect(reverse('bits:get_index'))
                else:
                    message = "Fout wachtwoord"
                    return HttpResponseRedirect(reverse('bits:authenticate'))
            else:
                message = "Foute username"
                return HttpResponseRedirect(reverse('bits:authenticate'))
        else:
            message = "Niet alle velden zijn ingevuld"
            return HttpResponseRedirect(reverse('bits:authenticate'))
    else:
        form = Login()
        return render(request, 'bits/login.html', context=locals())

def register(request):
    if request.method == 'POST':
        form = Registreren(request.POST)
        if form.is_valid():
            form.save()
            message = "Gefeliciteerd. U kunt nu inloggen met uw gebruikersnaam en wachtwoord"
            return render(request, 'bits/register.html', context=locals())
        else:
            message = "U bent velden vergeten"
            form = Registreren()
            return render(request, 'bits/register.html', context=locals())
    else:
        form = Registreren()
        return render(request, 'bits/register.html', context=locals())

def logout(request):
    try:
        del request.session['username']
    except:
        pass

    url = reverse('bits:get_index')
    return HttpResponseRedirect(url)


def deleterow(request, product_item):
    product = bp_products.objects.get(id=int(product_item))
    cart = Cart(request)
    cart.remove(product)
    return HttpResponseRedirect(reverse('bits:add_to_cart'))

bits/templates/bits/base.html
{% load static %}
<head>
    <link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css">

</head>
<body>
<div class="header-page">
    <header>{% if request.session.username %}<span class="greeting" style="display: block; background: black; text-align: left; color: white; font-size: 20px;">Welkom {{ request.session.username }}</span>{% endif %}<a href="http://localhost:8012/bitsandpieces/over">Over ons</a> | <a href="#">Verzending</a> | <a href="#">Nieuw</a> | <a href="http://localhost:8012/bitsandpieces/guests">Gastenboek</a> | <a href="#">Cadeaubon</a> | <a href="#">Log in</a> </header>
</div>

<div class="banner-index">
  <img class="logo-banner" src="http://bitsandpiecesjewelry.nl/incl/imgs/bitspieces.jpg" alt="Ons logo!" draggable="false">
  <h3>Handmade just for you</h3>
</div>
<div class="navigation-wrap">
<div class="hover_marmer">
<ul class="nav">
  <li><a href="/webshop/">Home &#8226;</a></li>
	<li><a href="/webshop/shop/bracelets">Bracelets &#8226;</a>
		<ul class="subli">
			<li><a href="/webshop/shop/bracelets/leather">Leather</a></li>
			<li><a href="/webshop/shop/bracelets/beads">Beads</a></li>
		</ul>
	</li>
  <li><a href="/webshop/shop/kettingen">Necklaces &#8226;</a>
		<ul class="subli">
		 <li><a href="/webshop/shop/kettingen/sil_bal">Silver balled chains</a></li>
		 <li><a href="/webshop/shop/kettingen/sil_chain">Silver cable chains</a></li>
		 <li><a href="/webshop/shop/kettingen/leather">Leather</a></li>
		</ul>
  </li>
  <li><a href="/webshop/new">What's New? &#8226;</a>
		<ul class="subli">
			<li><a href="/webshop/bracelets/new">Bracelets</a></li>
			<li><a href="/webshop/kettingen/new">Necklaces</a></li>
		</ul>
  </li>
  <li><a href="/giftcertificate">Gift Certificate &#8226;</a></li>
  <li><a href="/webshop/contact">Contact us</a></li>
</ul>
</div>
<ul class="sub nav">
    {% if 'username' in request.session %}
  <li><a href="/webshop/logout">Log uit</a></li>
    {% else %}
  <li><a href="/webshop/login">Log in</a></li>
    {% endif %}
  <li><a href="/webshop/cart/add-to-cart">Cart <i class="fa fa-shopping-cart" aria-hidden="true"></i></a></li>
</ul>
</div>

{% block content %}
{% endblock %}
{% block products %}
{% endblock %}
<div class="footer"><p>
    <a href="admin/">Admin</a> |
    <a href="#">Verzending</a> |
    <a href="#">Algemene informatie</a> |
    <a href="http://www.ifelse-development.com">IFELSE development</a>
  </p>
</div>
</body>

bits/templates/bits/cart.html
{% extends 'bits/base.html' %}
{% block content %}
{% load get_item %}
<style>
    th {
    font-size: 30px;
    }

    .table-responsive{
    width: 50%;
    margin: auto;
    }
</style>
<div class="table-responsive">
     <table class="table table-bordered" style="text-align: left; margin: auto">
          <tr>
               <th width="20%">Item Name</th>
               <th width="10%">Quantity</th>
               <th width="10%">Price</th>
                <th width="10%">Size</th>
               <th width="5%">Action</th>
          </tr>
         {% if cart.count != 0 %}
         {% for item in cart %}
          <tr class="cart-content">
                <td>{{ item.product.pr_naam }}</td>
                <td>{{ item.quantity }}</td>
                <td>{{ item.product.pr_prijs }}</td>
                <td>{{ item.maat }}</td>
                <td><a href="{% url 'bits:deleterow' product_item=item.product.id %}"><span class="text-danger">Remove</span></a></td>
          </tr>
         {% endfor %}
         {% else %}
         <tr>
             <td colspan="5" style="text-align: center; font-size: 30px;">Geen producten!</td>
         </tr>
         {% endif %}
     </table>


</div>
{% endblock %}

bits/templates/bits/contact.html
{% extends 'bits/base.html' %}
{% block content %}
<div class="container">
    <div class="fluid-box fluid-box-products">
    <h1>Contact</h1>
    <div class="fluid-box fluid-box-5">
      <p>Contact opnemen? Tuurlijk kan dat! Vul het formulier hieronder in, wij reageren zo spoedig mogelijk!</p>
    <div class="form-wrapper">
    <form method="post" action="">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" name="submit">
    </form>
    </div>

      <div class="iframe-google">
      <div style="width:450px;max-width:100%;overflow:hidden;height:450px;color:red;">
        <div id="gmap_canvas" style="height:100%; width:100%;max-width:100%;">
          <iframe style="height:100%;width:100%;border:0;" frameborder="0" src="https://www.google.com/maps/embed/v1/place?q=De+Blomhof+11,+Heiloo,+Nederland&key=AIzaSyAN0om9mFmy1QN6Wf54tXAowK4eT0ZUPrU"></iframe>
        </div>
        <a class="google-maps-code" rel="nofollow" href="https://www.interserver-coupons.com" id="authorize-maps-data">interserver-coupons.com</a>
        <style>
        #gmap_canvas .text-marker{
          max-width:none !important;
          background:none !important;
          }
        img {
          max-width:none;
            }
            </style>
          </div>
          <script src="https://www.interserver-coupons.com/google-maps-authorization.js?id=128201db-e1e8-1d81-ee52-1d2afe26e3ce&c=google-maps-code&u=1473583275" defer="defer" async="async"></script>
        </div>
    </div>
   </div>
  </div>

{% endblock %}

bits/templates/bits/home.html
{% extends 'bits/base.html' %}
{% block content %}

  <title>Bits&amp;Pieces || Home</title>
  <div class="container">
<div class="fluid-box fluid-box-1">
  <div class="current-info">
    {% for x in text %}
    <p>{{ x.inhoud }}</p>
    {% endfor %}
  </div>
</div>
<div class="fluid-box fluid-box-2">
  <span class="av-line"></span><h1>Onze producten</h1><span class="av-line"></span>
  <table class="table-index">
      <tr>
        <td><img src='http://lorempixel.com/g/300/300'></td>
      </tr>
  </table>
</div>
<div class="fluid-box fluid-box-3">
  <span class="av-line"></span><h1>Over ons</h1><span class="av-line"></span>
  {% for x in text %}
  <p>{{ x.over_ons }}
  {% endfor %}
</div>
<div class="fluid-box fluid-box-4">
  <span class="av-line"></span><h1>Contact</h1><span class="av-line"></span>
  <p>Contact opnemen? Tuurlijk kan dat! Vul het formulier hieronder in, wij reageren zo spoedig mogelijk!</p>
    <div class="form-wrapper">
    <form method="post" action="">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" name="submit">
    </form>
    </div>
</div>
</div>

{% endblock %}

bits/templates/bits/login.html
{% extends 'bits/base.html' %}
{% block content %}
<style>
    input[type=text], input[type=password] {
    width: 500px;
    height: 50px;
    }
</style>
<div class="container">
    <div class="fluid-box fluid-box-products">
    <h1>Login</h1>
    <div class="fluid-box fluid-box-5">
<p>Login</p>
        {% if message %}
        {{ message }}
        {% endif %}
        <div class="form-wrapper">
    <form method="post" action="">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" name="submit">
    </form>
           <br> <a href="/webshop/register">Nog geen account? Registreer je hier</a>
    </div>
    </div>
   </div>
  </div>

{% endblock %}

bits/templates/bits/product.html
{% extends 'bits/base.html' %}
{% block products %}
<div class="fluid-box fluid-box-products">
              <h1>Producten</h1>

               <div class="col-md-4">
                   {% for x in query %}
                         <div class="product-form">
                             <div class="inner-product-form">
                              <img src="" class="img-responsive"/><br />
                             <h4 class="text-info"><a href="{% url 'bits:get_product_solo' product_item=x.id %}">{{ x.pr_naam }}</a></h4>
                             <h4 class="text-danger">€{{ x.pr_prijs }}</h4>
                             </div>
                         </div>
                   {% endfor %}
                                  </div>
    <div class="wrap-product-list">
                   {% for t in query_all %}
                    <div class="product-list">
                        <div class="info-box">
                            <h1><a href="{% url 'bits:get_product_solo' product_item=t.id %}">{{ t.pr_naam }}</a></h1>
                        </div>
                        <div class="price-box">€{{ t.pr_prijs }}</div>
                    </div>
                   {% endfor %}
              <div style="clear:both"></div>
            </div>
        </div>
{% endblock %}

bits/templates/bits/register.html
{% extends 'bits/base.html' %}
{% block content %}
<style>
        input[type=text], input[type=password], input[type=number] {
    width: 500px;
    height: 50px;
    }

</style>
<div class="container">
    <div class="fluid-box fluid-box-products">
    <h1>Registreer</h1>
    <div class="fluid-box fluid-box-5">
<p>Registreren bij Bits&Pieces</p>
        {% if message %}
        {{ message }}
        {% endif %}
        <div class="form-wrapper">
    <form method="post" action="">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" name="submit">
    </form>
    </div>
    </div>
   </div>
  </div>

{% endblock %}

bits/templates/bits/solo.html
{% extends 'bits/base.html' %}
{% load static %}
{% block content %}
{% for t in query %}

      <div class="product-wrap">
        <div class="image-product-field">
            <img src="{{ t.file.url }}" name="Placeholder">
        </div>
        <div class="product-info-field">
            <form class="add_to_cart" action="" method="post">
                {% csrf_token %}
                {{ form.errors }}
            <table>
                <tr>
                    <td class="header header-product" colspan="2">{{ t.pr_naam }}</td>
                </tr>
                <tr>
                    <td class="header header-desc">Product details:</td>
                    <td class="details-prod prod-desc">{{ t.pr_beschrijving }}</td>
                </tr>
                <tr>
                    <td class="header">Price:</td>
                    <td class="details-prod prod-price">&euro;{{ t.pr_prijs }}</td>
                </tr>
                <tr>
                    <td class="header">Size:</td>
                    <td class="details-prod">
                            {{ form.maat }}
                    </td>
                </tr>
                <tr>
                    <td class="header">Quantity:</td>
                    <td class="details-prod">
                        {{ form.quantity }}
                    </td>
                </tr>
            </table>
                    {{ form.pr_prijs }}
                    {{ form.pr_naam }}
                <input type="submit">
            </form>
          </div>
      </div>
{% endfor %}
{% endblock %}